#!/usr/bin/env bash

mapfile -t input

res=0
prev=
for ((i = 0; i <= ${#input[@]} - 3; i++)); do
	sum=$((input[i] + input[i + 1] + input[i + 2]))
	[[ -n $prev ]] && {
		((sum > prev)) && ((res++))
	}
	prev=$sum
done

echo "$res"
