#!/usr/bin/env bash

res=0

IFS=',' read -r -a numbers

declare -A map
declare -A wins
declare -A drawn
grid=()

# store bingo cards rows and columns
i=0
while read -r -a line; do
	[[ -z "${line[*]}" ]] && continue

	box=$((i / 5))
	for j in "${!line[@]}"; do
		# echo "$box $i $j ${line[j]}"
		map["${line[j]}"]="${map[${line[j]}]} ${box}row${i} ${box}col${j}"
		grid["$box"]="${grid[$box]} ${line[$j]}"
	done
	((i++))
done

# loop over numbers and count wins in row/col
found=
last_num=
re='([0-9]+)'
for num in "${numbers[@]}"; do
	for pos in ${map[$num]}; do
		drawn["$num"]=true

		((++wins["$pos"] < 5)) && continue

		# check if is the last box
		[[ "$pos" =~ $re ]]
		box="${BASH_REMATCH[1]}"
		if ((${#grid[@]} == 1)) && [[ -n "${grid[$box]}" ]]; then
			found="$pos"
			last_num="$num"
			# echo last $num $pos ${#grid[@]}
			break
		fi

		# unset bingo card
		unset "grid[$box]"
		# echo $num $pos ${#grid[@]}
	done
	[[ -n "$found" ]] && break
done

[[ "$found" =~ $re ]]
box="${BASH_REMATCH[1]}"

for num in ${grid[$box]}; do
	[[ -z "${drawn[$num]}" ]] && ((res += num))
done

echo $((res * last_num))
