#!/usr/bin/env bash

hor=0
dep=0
while read -ra input; do
	case "${input[0]}" in
	forward) ((hor += input[1])) ;;
	up) ((dep -= input[1])) ;;
	down) ((dep += input[1])) ;;
	esac
done

echo $((hor * dep))
