#!/usr/bin/env bash
set -e

fatal() {
	echo '[FATAL]:' "$*" >&2
	exit 1
}

usage() {
	cat <<-EOF
		Usage: ${0##*/} <day> [part]

		Options:
		  -t Use test input 
		  -x Debug mode
		  -w Watch mode
	EOF

	exit 0
}

test_mode=
debug_mode=
watch_mode=

while getopts "htxw" opt; do
	case "$opt" in
	h) usage ;;
	t) test_mode=true ;;
	x) debug_mode=true ;;
	w) watch_mode=true ;;
	\?) fatal "invalid argument: -$OPTARG" ;;
	esac
done
shift $((OPTIND - 1))

day="$1"
part="${2:-1}"
cd -- "$(dirname -- "${BASH_SOURCE[0]}")"
year=${PWD##*/}

# if no arguments, use fzf to select day
(($# >= 1)) || {
	command -v fzf &>/dev/null || usage

	file=$(cd days && printf '%s\n' day* | grep -v 'day00$' | fzf --tac)

	re='^day0?([0-9]+)_([0-9]+)$'
	[[ $file =~ $re ]] || fatal "invalid file: $file"

	day="${BASH_REMATCH[1]}"
	part="${BASH_REMATCH[2]}"
}

printf -v day_padded '%02d' "$day"
input_file="input/input$day_padded"
day_file="days/day${day_padded}_$part"

# download input if does not exist
[[ -s $input_file ]] || {
	[[ -s .env ]] || fatal ".env file not found"

	# shellcheck disable=SC1091
	source .env

	echo "downloading input for day $day..."
	curl -fsS \
		-b "session=$SESSION_ID" \
		-o "$input_file" \
		"https://adventofcode.com/$year/day/$day/input"
}

# check day file
[[ -s $day_file ]] || {
	cp days/day00 "$day_file"
	fatal "file not found: ${day_file##*/}"
}

# ensure its executable
[[ -x $day_file ]] || chmod +x "$day_file"

# load input, test mode scrapes the sample input
input=$(<"$input_file")
[[ -n $test_mode ]] && {
	input=$(curl -fsS "https://adventofcode.com/$year/day/$day")
	input=$(
		sed -nE '
		/<\/code><\/pre>/q
		/<pre><code>/,/<\/code><\/code><\/pre>/{
			s/<\/?(code|pre)>//g
			p
		}' <<<"$input"
	)

	[[ -n $input ]] || fatal 'test input not found'
}

# debug mode adds -x
runner=("$day_file")
[[ -n $debug_mode ]] && runner=(bash -x "$day_file")

echo "running $day_file"
"${runner[@]}" <<<"$input"

# watch mode keeps running every change
[[ -n $watch_mode ]] && {
	command -v inotifywait &>/dev/null || fatal 'inotifywait command not found'

	while inotifywait -q -e modify "$day_file"; do
		sleep 0.05
		echo 'file changed'
		"${runner[@]}" <<<"$input"
	done
}
